spring:
  application:
    name: settlement-system

  config:
    import: "optional:file:.env[.properties]"  # .env 파일 직접 로드

  main:
    allow-bean-definition-overriding: true
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
jwt:
  secret-key: ${SECRET_KEY}
  access-key-expiration-s: ${ACCESS_KEY_EXPIRATION_SECONDS}
  refresh-key-expiration-s: ${REFRESH_KEY_EXPIRATION_SECONDS}


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

